[package]
name = "rose-gltf"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.1"
clap = "3.1"
glam = "0.20.5"
gltf = "1.0.0"
gltf-json = "1.0.0"
roselib = { git = "https://github.com/exjam/rose-tools", rev = "74e440dbba51f1f0631ba24aff3a72f918e306b8" }
serde_json = "1"
