[package]
name = "make-lit"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
clap = { workspace = true }
glam = { workspace = true }
image = { workspace = true }
roselib = { workspace = true }
