[package]
name = "make-lit"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }

[dependencies]
clap = { workspace = true }
glam = { workspace = true }
image = { workspace = true }
rose-file-lib = { path = "../rose-file-lib" }
